-- Seed data ported from assets/js/pricing-data.js — safe to re-run after TRUNCATE.

-- Install zones
insert into install_zones (id, label, multiplier, note) values (1, 'Zone 1 — Attic/horizontal, easy access', 1.0, 'Minimal material modification');
insert into install_zones (id, label, multiplier, note) values (2, 'Zone 2 — Attic/horizontal, moderate access', 1.1, 'Additional plenum/drain/support allowance');
insert into install_zones (id, label, multiplier, note) values (3, 'Zone 3 — Closet/vertical, moderate access', 1.05, 'Plenum and drain adaptation allowance');
insert into install_zones (id, label, multiplier, note) values (4, 'Zone 4 — Closet, tight/restricted access', 1.2, 'More fabrication/support material');
insert into install_zones (id, label, multiplier, note) values (5, 'Zone 5 — Difficult access / structural modification', 1.35, 'Higher plenum, drain and support allowance');

-- Equipment tonnage pricing
insert into equipment_tonnage_pricing (equipment_type, tonnage, description, low_price, high_price) values ('condenser', 1.5, 'Single speed condenser', 2000, 2200);
insert into equipment_tonnage_pricing (equipment_type, tonnage, description, low_price, high_price) values ('condenser', 2, 'Single speed condenser', 2200, 2420);
insert into equipment_tonnage_pricing (equipment_type, tonnage, description, low_price, high_price) values ('condenser', 2.5, 'Single speed condenser', 2300, 2530);
insert into equipment_tonnage_pricing (equipment_type, tonnage, description, low_price, high_price) values ('condenser', 3, 'Single speed condenser', 2500, 2750);
insert into equipment_tonnage_pricing (equipment_type, tonnage, description, low_price, high_price) values ('condenser', 3.5, 'Single speed condenser', 2800, 3080);
insert into equipment_tonnage_pricing (equipment_type, tonnage, description, low_price, high_price) values ('condenser', 4, 'Single speed condenser', 3100, 3410);
insert into equipment_tonnage_pricing (equipment_type, tonnage, description, low_price, high_price) values ('condenser', 5, 'Single speed condenser', 3500, 3850);
insert into equipment_tonnage_pricing (equipment_type, tonnage, description, low_price, high_price) values ('condenser', 6, 'Single speed condenser', 5000, 5500);
insert into equipment_tonnage_pricing (equipment_type, tonnage, description, low_price, high_price) values ('coil', 1.5, 'Cased Coil', 750, 825);
insert into equipment_tonnage_pricing (equipment_type, tonnage, description, low_price, high_price) values ('coil', 2, 'Cased Coil', 850, 935);
insert into equipment_tonnage_pricing (equipment_type, tonnage, description, low_price, high_price) values ('coil', 2.5, 'Cased Coil', 1000, 1100);
insert into equipment_tonnage_pricing (equipment_type, tonnage, description, low_price, high_price) values ('coil', 3, 'Cased Coil', 1000, 1100);
insert into equipment_tonnage_pricing (equipment_type, tonnage, description, low_price, high_price) values ('coil', 3.5, 'Cased Coil', 1300, 1430);
insert into equipment_tonnage_pricing (equipment_type, tonnage, description, low_price, high_price) values ('coil', 4, 'Cased Coil', 1400, 1540);
insert into equipment_tonnage_pricing (equipment_type, tonnage, description, low_price, high_price) values ('coil', 5, 'Cased Coil', 1500, 1650);
insert into equipment_tonnage_pricing (equipment_type, tonnage, description, low_price, high_price) values ('coil', 6, 'Cased Coil', 1800, 1980);

-- Furnace tiers
insert into furnace_tiers (tier_key, label, low_price, high_price) values ('80std', '80% AFUE — single-stage (standard)', 1500, 1800);
insert into furnace_tiers (tier_key, label, low_price, high_price) values ('96two', '96% AFUE — two-stage', 2400, 2800);
insert into furnace_tiers (tier_key, label, low_price, high_price) values ('96mod', '96% AFUE — variable-speed / modulating', 3200, 3800);

-- Membership plans
insert into membership_plans (name, visits_per_year, price_per_year, features) values ('Basic Plan', 1, 149, '["1 annual tune-up & safety inspection", "Filter check", "10% discount on repairs"]'::jsonb);
insert into membership_plans (name, visits_per_year, price_per_year, features) values ('Comfort Plan', 2, 249, '["2 seasonal tune-ups (spring & fall)", "Priority scheduling", "15% discount on repairs", "No overtime charges"]'::jsonb);
insert into membership_plans (name, visits_per_year, price_per_year, features) values ('Premium Plan', 2, 349, '["2 seasonal tune-ups + 1 courtesy visit", "Same-day priority scheduling", "20% discount on repairs & parts", "Free filter replacements", "No overtime charges"]'::jsonb);

-- Condenser Change materials
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('condenser_change', 'MATERIALS', 'Equipment', '3-ton condenser unit (size below)', 'EA', 1, 2500, 2750, 'AHRI-matched, 208/230V-1ph — confirm refrigerant type (R-410A vs A2L R-454B)', 'New outdoor condensing unit sized to match the existing coil/furnace.', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('condenser_change', 'MATERIALS', 'Refrigeration', 'Refrigerant charge', 'OZ', 0.08, 200, 250, 'R-410A or A2L per system, ~8-10 lb typical for 3-ton', 'Refrigerant weighed to nameplate spec, adjusted for line length.', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('condenser_change', 'MATERIALS', 'Refrigeration', 'POE refrigerant oil', 'OZ', 1, 20, 22, 'POE, viscosity per condenser OEM spec', 'Compatible lubricant added per manufacturer spec.', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('condenser_change', 'MATERIALS', 'Refrigeration', 'Line-set flare nuts / couplings', 'EA', 0, 15, 16.5, 'Match existing line-set OD (3/8" & 3/4" typical 3-ton)', 'Reconnects line set to new condenser fittings.', 'Check');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('condenser_change', 'MATERIALS', 'Brazing', 'Nitrogen (job usage)', 'OZ', 1, 15, 16.5, 'Per-job cylinder rental/fill portion', 'Purge gas during brazing and pressure test.', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('condenser_change', 'MATERIALS', 'Electrical', 'Electrical whip', 'EA', 0, 35, 38.5, 'Sized to unit MCA/MOCP, typically 10/3 or 8/3 AWG', 'Power connection from disconnect to condenser.', 'Check');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('condenser_change', 'MATERIALS', 'Electrical', 'Disconnect switch', 'EA', 0, 40, 44, 'Non-fused pull-out, 60A, weatherproof', 'Local electrical disconnect at the condenser.', 'Check');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('condenser_change', 'MATERIALS', 'Installation', 'Condenser pad', 'EA', 0, 60, 66, 'Composite, 36"x36"x3" or equivalent', 'Level composite/concrete base for the new unit.', 'Check');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('condenser_change', 'MATERIALS', 'Installation', 'Pad shims / leveling material', 'Bag', 0, 10, 11, 'Composite shims, assorted thickness', 'Fine-levels the pad on uneven ground.', 'Check');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('condenser_change', 'MATERIALS', 'Electrical', 'Wire nuts / tape / anti-oxidant compound', 'Bag', 1, 15, 16.5, 'UL-listed connectors, anti-oxidant paste', 'Electrical connection finishing, incl. aluminum whip prep.', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('condenser_change', 'MATERIALS', 'Equipment', 'Liquid-line filter drier', 'EA', 1, 50, 80, 'Sized to line OD and system tonnage', 'Replaced any time the system is opened; mandatory after contamination/burnout.', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('condenser_change', 'ACCESSORIES', 'Accessory', 'Hard start kit', 'EA', 0, 60, 66, 'Single-phase, sized to compressor RLA', 'Reduces compressor inrush current; recommended on long line runs or weak supply.', 'Optional');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('condenser_change', 'ACCESSORIES', 'Accessory', 'Whole-unit surge protector', 'EA', 0, 80, 88, 'Line-side, condenser-rated', 'Protects condenser electronics from grid/storm surges.', 'Optional');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('condenser_change', 'ACCESSORIES', 'Accessory', 'Low-ambient control kit', 'EA', 0, 70, 77, 'Fan-cycling switch or head-pressure control', 'Enables reliable operation below manufacturer''s rated ambient minimum.', 'Optional');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('condenser_change', 'ACCESSORIES', 'Accessory', 'Compressor crankcase heater', 'EA', 0, 50, 55, 'Wrap-style, sized to compressor', 'Prevents refrigerant migration into the compressor in cold weather (if not factory-included).', 'Optional');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('condenser_change', 'ACCESSORIES', 'Accessory', 'Sound blanket / compressor cover', 'EA', 0, 90, 99, 'Universal fit, weatherproof', 'Reduces operating noise — common customer request.', 'Optional');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('condenser_change', 'ACCESSORIES', 'Accessory', 'Condenser security cage', 'EA', 0, 150, 165, 'Powder-coated steel, ground-anchored', 'Theft deterrent for the outdoor unit.', 'Optional');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('condenser_change', 'ACCESSORIES', 'Accessory', 'Line-set cover / channel kit', 'EA', 0, 45, 49.5, '10 ft kit, paintable PVC', 'Cosmetic cover for exposed exterior line set.', 'Check');

-- Coil Change materials
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Refrigeration', 'Evaporator coil – matched replacement (size below)', 'EA', 1, 1000, 1100, NULL, 'OEM/matched coil; size and refrigerant dependent', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Refrigeration', 'TXV / metering device', 'EA', 0, 80, 200, NULL, 'If not supplied with coil or replacement is required', 'Check');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Refrigeration', 'Filter-drier', 'EA', 0, 50, 80, NULL, 'Replace when refrigeration circuit is opened', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Refrigeration', 'Refrigerant R-410A ($200/25lb allowance)', 'OZ', 0.08, 200, 250, 'EPA-approved, dual-port, R-410A/A2L rated', 'Allowance only; use actual refrigerant and charge requirement', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Refrigeration', 'Nitrogen / pressure-test allowance', 'LOT', 1, 15, 30, NULL, 'Purging and pressure testing', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Refrigeration', 'Copper tube 3/8"', 'FT', 0.25, 20, 50, NULL, 'Couplings, elbows and brazing material', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Refrigeration', 'Copper tube 1"', 'FT', 0.25, 40, 80, NULL, NULL, 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Refrigeration', 'Copper fittings', 'Bag', 1, 30, 50, NULL, 'Couplings, elbows and brazing material', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Refrigeration', 'Copper brazing alloy', 'LOT', 1, 5, 8, NULL, 'Couplings, elbows and brazing material', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Refrigeration', 'Refrigerant pipe insulation', '8FT', 2, 24, 36, NULL, 'Replace disturbed insulation', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Air Distribution', 'Duct mastic / approved sealant', 'EA', 1, 15, 35, NULL, 'Seal disturbed duct joints', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Air Distribution', 'UL-181 foil tape', 'Roll', 0.5, 15, 30, NULL, 'Approved duct sealing tape', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Air Distribution', 'Zip ties for duct branches', 'Pack', 0.25, 50, 80, NULL, '2ft to 3ft long zip ties for ducting', 'Check');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Air Distribution', 'Air filter', 'EA', 1, 40, 60, NULL, NULL, 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Drainage', 'PVC tube 3/4", 8ft', 'EA', 1, 10, 15, NULL, 'Typically PVC/CPVC; verify existing installation', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Drainage', 'PVC fitting 3/4" elbow', 'Bag', 1, 6, 10, NULL, NULL, 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Drainage', 'PVC fitting 3/4" straight', 'Bag', 1, 6, 10, NULL, NULL, 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Drainage', 'P-trap / condensate trap', 'EA', 1, 15, 40, NULL, 'Configuration dependent', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Drainage', 'Cleanout / vent fittings', 'LOT', 1, 10, 30, NULL, 'For serviceability and drain configuration', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Safety', 'Primary drain float/overflow switch', 'EA', 1, 25, 50, NULL, 'Safety shutoff; application dependent', 'Check');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Equipment Support', 'Structural support / hanging hardware', 'LOT', 1, 75, 150, NULL, 'Angles, rods, brackets, anchors', 'Check');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Equipment Support', 'Vibration isolation pads', 'Set', 0, 20, 75, NULL, 'Where applicable', 'Check');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Electrical', 'Low-voltage wire/connectors', 'LOT', 1, 15, 50, NULL, 'For safety switches/controls', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Electrical', 'Wire nuts', 'Bag', 1, 10, 30, NULL, 'Miscellaneous electrical material for furnace/EEV/switch connections', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Electrical', 'Electric conduit', 'Bag', 0, 10, 25, NULL, NULL, 'Check');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Electrical', 'Wire cover', 'Bag', 0, 10, 15, NULL, NULL, 'Check');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Electrical', 'Conduit fitting with strain relief', 'EA', 1, 1, 3, NULL, NULL, 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Electrical', 'Wire terminals', 'EA', 4, 1, 3, NULL, NULL, 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Cleaning', 'Cleaning/sanitizing materials', 'LOT', 1, 15, 50, NULL, 'Coil/pan/drain area', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Permits', 'Permit/inspection allowance', 'LOT', 1, 50, 250, NULL, 'Local jurisdiction dependent', 'Check');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Disposable', 'Old equipment disposal fee / plastic packaging recycle fee', 'EA', 1, 150, 250, NULL, NULL, 'Check');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('coil_change', 'MATERIALS', 'Cleaning', 'Bucket', 'EA', 1, 15, 20, NULL, NULL, 'Yes');

-- Furnace Change materials (starter template)
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('furnace_change', 'MATERIALS', 'Equipment', 'Furnace unit (tier below)', 'EA', 1, 1500, 1800, NULL, 'Sized to duct system and BTU load', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('furnace_change', 'MATERIALS', 'Venting', 'Flue / vent pipe extension', 'LOT', 1, 60, 150, NULL, 'Category I or PVC intake/exhaust depending on tier', 'Check');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('furnace_change', 'MATERIALS', 'Gas', 'Gas line / flex connector', 'EA', 1, 35, 75, NULL, 'Sized to furnace BTU input', 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('furnace_change', 'MATERIALS', 'Electrical', 'Electrical whip / dedicated circuit', 'EA', 0, 35, 60, NULL, NULL, 'Check');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('furnace_change', 'MATERIALS', 'Drainage', 'Condensate drain / PVC (high-efficiency only)', 'LOT', 0, 20, 45, NULL, 'Required for 90%+ AFUE units', 'Check');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('furnace_change', 'MATERIALS', 'Air', 'Air filter', 'EA', 1, 20, 35, NULL, NULL, 'Yes');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('furnace_change', 'MATERIALS', 'Permits', 'Permit/inspection allowance', 'LOT', 1, 50, 200, NULL, NULL, 'Check');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('furnace_change', 'MATERIALS', 'Disposable', 'Old equipment disposal fee', 'EA', 1, 75, 125, NULL, NULL, 'Check');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('furnace_change', 'MATERIALS', 'Electrical', 'Wire nuts / misc electrical', 'Bag', 1, 10, 20, NULL, NULL, 'Yes');

-- Drainpan install materials + labor
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('drainline_maintenance', 'MATERIALS', 'Drainage', 'Secondary/emergency drain pipe & fittings (male threaded)', 'LOT', 1, 10, 15, '3/4 in. PVC Sch 40 90-deg fitting (10-pack), male threaded', 'If required by installation', NULL);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('drainline_maintenance', 'MATERIALS', 'Drainage', 'Secondary/emergency drain pipe & fittings (female threaded)', 'LOT', 1, 10, 15, '3/4 in. PVC Sch 40 90-deg fitting (10-pack), female threaded', NULL, NULL);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('drainline_maintenance', 'MATERIALS', 'Drainage', 'Secondary/emergency drain pan', 'EA', 1, 75, 200, 'Drip pan, 27" x 48"', 'Size to equipment footprint', NULL);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('drainline_maintenance', 'MATERIALS', 'Safety', 'Secondary pan float switch', 'EA', 1, 25, 50, '3/4" float switch, L-shape HVAC safety switch', 'Overflow protection', NULL);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('drainline_maintenance', 'MATERIALS', 'Safety', 'Additional drain-line safety switch', 'EA', 0, 25, 50, NULL, 'Optional additional protection', NULL);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('drainline_maintenance', 'MATERIALS', 'Equipment Support', 'Base/support platform', 'EA', 1, 75, 150, NULL, 'Wood/metal/composite support as required', NULL);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec, notes, optional_flag) values ('drainline_maintenance', 'MATERIALS', 'Labor', 'Installation labor (1 technician)', 'HR', 2, 30, 50, NULL, NULL, NULL);

-- Drain line routine maintenance items (flat-priced -> low = high)
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('drainline_maintenance', 'MATERIALS', 'Drain pipe maintenance', 'Vacuum cleaner (shopvac)', 'EA', 1, 100, 100);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('drainline_maintenance', 'MATERIALS', 'Drain pipe maintenance', 'Hose to PVC pipe adapter', 'EA', 1, 20, 20);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('drainline_maintenance', 'MATERIALS', 'Drain pipe maintenance', 'P-trap (to maintain static pressure)', 'EA', 2, 20, 20);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('drainline_maintenance', 'MATERIALS', 'Drain pipe maintenance', 'Garden hose adapter', 'EA', 2, 1, 1);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('drainline_maintenance', 'MATERIALS', 'Drain pipe maintenance', 'Garden hose valve', 'EA', 2, 1, 1);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('drainline_maintenance', 'MATERIALS', 'Drain pipe maintenance', 'Swivel adapter (coil cleaning)', 'EA', 1, 8, 8);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('drainline_maintenance', 'MATERIALS', 'Drain pipe maintenance', '1/4" clear plastic hose', 'EA', 1, 5, 5);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('drainline_maintenance', 'MATERIALS', 'Drain pipe maintenance', 'Garden hose, lightweight', 'EA', 1, 50, 50);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('drainline_maintenance', 'MATERIALS', 'Drain pipe maintenance', 'Vinegar (algae prevention)', 'EA', 1, 3, 3);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('drainline_maintenance', 'MATERIALS', 'Drain pipe maintenance', 'PVC adapters 3/4" straight', 'Bag', 1, 10, 10);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('drainline_maintenance', 'MATERIALS', 'Drain pipe maintenance', 'PVC adapters 3/4" elbow', 'Bag', 1, 10, 10);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('drainline_maintenance', 'MATERIALS', 'Drain pipe maintenance', 'PVC pipe', 'EA', 1, 10, 10);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('drainline_maintenance', 'MATERIALS', 'Drain pipe maintenance', 'Pipe cleaner (snake)', 'EA', 1, 8, 8);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('drainline_maintenance', 'MATERIALS', 'Drain pipe maintenance', 'Pipe cleaner brush', 'EA', 1, 8, 8);

-- Labor rates
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('labor', 'MATERIALS', 'Labor', 'Transportation', 'HR', 1, 50, 50);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('labor', 'MATERIALS', 'Labor', '1 Technician', 'HR', 1, 50, 50);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('labor', 'MATERIALS', 'Labor', '1 Lead', 'HR', 1, 80, 80);

-- Plenum type price table (stored as material_catalog rows tagged by category)
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec) values ('plenum_change', 'MATERIALS', 'CCoil', 'CCoil plenum — Insulated SM — cabinet A (14X21)', 'EA', 1, 120, 120, 'Insulated Galvanized Sheet Metal supply Plenum 14.5x20.5x36');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec) values ('plenum_change', 'MATERIALS', 'CCoil', 'CCoil plenum — Insulated SM — cabinet B (17.5X21)', 'EA', 1, 130, 130, 'Insulated Galvanized Sheet Metal supply Plenum 17x20.5x36');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec) values ('plenum_change', 'MATERIALS', 'CCoil', 'CCoil plenum — Insulated SM — cabinet C (21X21)', 'EA', 1, 160, 160, 'Insulated Galvanized Sheet Metal Supply Plenum 19.5x20.5x36');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec) values ('plenum_change', 'MATERIALS', 'CCoil', 'CCoil plenum — Insulated SM — cabinet D (24.5X21)', 'EA', 1, 180, 180, 'Insulated Galvanized Sheet Metal Supply Plenum');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec) values ('plenum_change', 'MATERIALS', 'Furnace', 'Furnace plenum — Insulated SM — cabinet A (14X26)', 'EA', 1, 150, 150, 'Insulated Galvanized Sheet Metal Supply Plenum');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec) values ('plenum_change', 'MATERIALS', 'Furnace', 'Furnace plenum — Insulated SM — cabinet B (17.5X26)', 'EA', 1, 180, 180, 'Insulated Galvanized Sheet Metal Supply Plenum');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec) values ('plenum_change', 'MATERIALS', 'Furnace', 'Furnace plenum — Insulated SM — cabinet C (21X26)', 'EA', 1, 200, 200, 'Insulated Galvanized Sheet Metal Supply Plenum');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec) values ('plenum_change', 'MATERIALS', 'Furnace', 'Furnace plenum — Insulated SM — cabinet D (24.5X26)', 'EA', 1, 250, 250, 'Insulated Galvanized Sheet Metal Supply Plenum');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec) values ('plenum_change', 'MATERIALS', 'CCoil', 'CCoil plenum — Sheetmetal — cabinet A (14X21)', 'EA', 1, 50, 50, 'Sheetmetal plenum');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec) values ('plenum_change', 'MATERIALS', 'CCoil', 'CCoil plenum — Sheetmetal — cabinet B (17.5X21)', 'EA', 1, 70, 70, 'Sheetmetal plenum');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec) values ('plenum_change', 'MATERIALS', 'CCoil', 'CCoil plenum — Sheetmetal — cabinet C (21X21)', 'EA', 1, 90, 90, 'Sheetmetal plenum');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec) values ('plenum_change', 'MATERIALS', 'CCoil', 'CCoil plenum — Sheetmetal — cabinet D (24.5X21)', 'EA', 1, 100, 100, 'Sheetmetal plenum');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec) values ('plenum_change', 'MATERIALS', 'Furnace', 'Furnace plenum — Sheetmetal — cabinet A (14X26)', 'EA', 1, 80, 80, 'Sheetmetal plenum');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec) values ('plenum_change', 'MATERIALS', 'Furnace', 'Furnace plenum — Sheetmetal — cabinet B (17.5X26)', 'EA', 1, 100, 100, 'Sheetmetal plenum');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec) values ('plenum_change', 'MATERIALS', 'Furnace', 'Furnace plenum — Sheetmetal — cabinet C (21X26)', 'EA', 1, 120, 120, 'Sheetmetal plenum');
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost, spec) values ('plenum_change', 'MATERIALS', 'Furnace', 'Furnace plenum — Sheetmetal — cabinet D (24.5X26)', 'EA', 1, 150, 150, 'Sheetmetal plenum');

-- Duct collars
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('plenum_change', 'MATERIALS', 'Duct Collar', 'Duct collar 6"', 'EA', 4, 25, 25);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('plenum_change', 'MATERIALS', 'Duct Collar', 'Duct collar 8"', 'EA', 3, 30, 30);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('plenum_change', 'MATERIALS', 'Duct Collar', 'Duct collar 10"', 'EA', 3, 35, 35);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('plenum_change', 'MATERIALS', 'Duct Collar', 'Duct collar 12"', 'EA', 1, 50, 50);
insert into material_catalog (worksheet, item_group, category, item_name, unit, default_qty, low_unit_cost, high_unit_cost) values ('plenum_change', 'MATERIALS', 'Duct Collar', 'Duct collar 16"', 'EA', 0, 60, 60);
